version: "3.7"

services: 
 satdress:
    build: . 
    container_name: satdress
    environment:
      - PORT=17422
      - DOMAIN=satoshis.se
      - SECRET=soryakfqomdu3r9d5b1x
      - SITE_OWNER_URL=https://maxmanbtc.com
      - SITE_OWNER_NAME=@maxmanbtc
      - SITE_NAME=Satoshis.se
    ports:
      - 17422:17422
    volumes:
      - satdress-data:/satoshis.se

volumes:
  satdress-data:
    name: satdress-data

